name: Tests

on:
    - push
    - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run pytest
      id: wk02-area-test
      run: python -m pytest tests/
